FROM elasticsearch:2
MAINTAINER o2r project <http://o2r.info>

# https://www.elastic.co/blog/elasticsearch-docker-plugin-management
RUN /usr/share/elasticsearch/bin/plugin install --batch mapper-attachments